model_save_path: models/model_experiment_2.pkl
pipeline_save_path: models/pipeline_experiment_2.pkl
data_load_config:
  data_path: data/heart.csv
  split_config:
    val_size: 0.1
    random_state: 42
feature_config:
  target_column: target
  replace_zeros: true
  raw_features:
    numeric_features:
      - age
      - trestbps
      - chol
      - thalach
      - oldpeak
    categorical_features:
      - thal
      - ca
      - slope
      - exang
      - restecg
      - fbs
      - cp
      - sex
  statistical_features:
    build: false
    features:
      - sum
      - var
      - median
      - mean
      - std
      - max
      - min
  random_projection_features:
    build: true
    n_features: 5
  polynomial_features:
    build: true
    degree: 2
  k_means_features:
    build: true
model_config:
  model: extra_trees
  random_state: 42
  params:
    n_estimators: 100
    max_depth: 10
evaluation_config:
  metric_file_path: reports/metrics_experiment_2.yaml
  metrics:
    - accuracy
    - f1
    - precision
    - recall
